In [1]:
%matplotlib inline
#import seaborn as sns
#import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
#import sqlite3

survey_data = pd.read_csv('data/questionnaire.csv')
maps_data = pd.read_csv('data/map-data.csv')




survey_data['participant_id']=survey_data['Q51_1'].astype(np.int64)

survey_data.head(5)
survey_data.describe()

,Progress,Duration (in seconds),RecipientLastName,RecipientFirstName,RecipientEmail,ExternalReference,LocationLatitude,LocationLongitude,Q51_1,Q2_1,...,Q4_1,Q5_1,Q6_1,Q7_1,Q30_1,Q33_9_TEXT,Q44_1,Q51_1 - Sentiment Score,Q51_1 - Sentiment Polarity,participant_id
count,59.0,59.000000,0.0,0.0,0.0,0.0,59.000000,59.000000,59.000000,59.000000,...,59.000000,59.000000,59.000000,59.000000,59.000000,0.0,59.000000,50.000000,50.0,59.000000
mean,100.0,8290.000000,NaN,NaN,NaN,NaN,41.929228,-89.737303,35.542373,8.728814,...,3.355932,11.898305,6.864407,4.694915,26.949153,NaN,3.627119,0.200000,0.0,35.542373
std,0.0,19599.804026,NaN,NaN,NaN,NaN,2.328041,3.863701,20.820515,4.037883,...,3.066857,4.539842,4.439080,5.136933,10.404614,NaN,2.355465,0.571429,0.0,20.820515
min,100.0,604.000000,NaN,NaN,NaN,NaN,32.813705,-97.821999,1.000000,1.000000,...,0.000000,1.000000,0.000000,0.000000,20.000000,NaN,0.000000,-1.000000,0.0,1.000000
25%,100.0,1731.000000,NaN,NaN,NaN,NaN,43.038895,-87.935699,17.500000,5.000000,...,1.000000,9.000000,3.000000,1.000000,21.000000,NaN,2.000000,0.000000,0.0,17.500000
50%,100.0,2616.000000,NaN,NaN,NaN,NaN,43.038895,-87.906502,34.000000,8.000000,...,3.000000,12.000000,7.000000,3.000000,22.000000,NaN,4.000000,0.000000,0.0,34.000000
75%,100.0,4738.500000,NaN,NaN,NaN,NaN,43.038895,-87.906502,54.500000,12.000000,...,5.000000,15.000000,10.000000,7.000000,29.000000,NaN,5.000000,1.000000,0.0,54.500000
max,100.0,92662.000000,NaN,NaN,NaN,NaN,43.040695,-87.651703,69.000000,17.000000,...,10.000000,20.000000,18.000000,18.000000,76.000000,NaN,9.000000,1.000000,0.0,69.000000

In [4]:
data=pd.merge(maps_data, survey_data, on="participant_id", how="left")
data.describe()
data.head(5)
data.to_csv('data/masterData.csv', sep='\t')

In [5]:
data.describe()
data.head(5)

,new_part_id,participant_id,group_num,background,kernel1,bandwidth1,metric1,min_hotspots1,max_hotspots1,min_circles1,...,Q41,Q42,Q43,Q44_1,Q45,Q46,Q51_1 - Sentiment,Q51_1 - Sentiment Score,Q51_1 - Sentiment Polarity,Q51_1 - Topics
0,1,1,2,tech,gaussian,0.0025,euclidean,4,20,5,...,No,Neither agree nor disagree,Somewhat agree,5.0,Neutral,Neutral,NaN,NaN,NaN,NaN
1,2,2,1,none,gaussian,0.0050,euclidean,13,11,17,...,Yes,Somewhat agree,Somewhat disagree,2.0,Somewhat Libertarian,Somewhat fiscally conservative,Neutral,0.0,0.0,Unknown
2,3,3,1,none,gaussian,0.0050,euclidean,10,24,50,...,Yes,Agree,Somewhat agree,9.0,Authoritarian,Fiscally conservative,Neutral,0.0,0.0,Unknown
3,4,4,1,none,linear,0.0050,euclidean,5,15,8,...,No,Agree,Agree,5.0,Neutral,Somewhat fiscally conservative,Neutral,0.0,0.0,Unknown
4,5,6,1,none,gaussian,0.0050,euclidean,9,16,19,...,Yes,Agree,Somewhat agree,1.0,Somewhat Authoritarian,Somewhat fiscally conservative,Neutral,0.0,0.0,Unknown

In [6]:
data_g1= data[data['group_num']==1]

data_g1.to_csv('data/g1.csv', sep='\t')

In [7]:
data_g2= data[data['group_num']==2]

data_g2.to_csv('data/g2.csv', sep='\t')

In [8]:
data_g3= data[data['group_num']==3]

data_g3.to_csv('data/g3.csv', sep='\t')

In [4]:
data = pd.read_csv('data/anovaFriendly.csv')

In [41]:
data['k']=0
data['b']=0
data['d']=0
data.head(10)

,new_part_id,participant_id,group_num,background,complexity,min_hotspots,max_hotspots,min_circles,max_circles,kernel,bandwidth,distance,k,b,d
0,1,1,2,tech,1,4,20,5,10,gaussian,0.0025,euclidean,0,0,0
1,2,2,1,none,1,13,11,17,14,gaussian,0.0050,euclidean,0,0,0
2,3,3,1,none,1,10,24,50,65,gaussian,0.0050,euclidean,0,0,0
3,4,4,1,none,1,5,15,8,15,linear,0.0050,euclidean,0,0,0
4,5,6,1,none,1,9,16,19,13,gaussian,0.0050,euclidean,0,0,0
5,6,7,1,none,1,50,90,50,55,tophat,0.0050,manhattan,0,0,0
6,7,8,2,tech,1,40,55,20,30,gaussian,0.0050,euclidean,0,0,0
7,8,10,1,none,1,6,12,9,14,gaussian,0.0050,euclidean,0,0,0
8,9,11,1,none,1,10,18,6,10,gaussian,0.0050,euclidean,0,0,0
9,10,12,1,none,1,17,50,5,30,gaussian,0.0050,euclidean,0,0,0

In [42]:
data.loc[data['kernel'] != 'gaussian', 'k']=1
data.loc[(data['bandwidth'] != 0.005), 'b']=1
data.loc[data['distance'] != 'euclidean', 'd']=1

In [43]:
data.head(10)

,new_part_id,participant_id,group_num,background,complexity,min_hotspots,max_hotspots,min_circles,max_circles,kernel,bandwidth,distance,k,b,d
0,1,1,2,tech,1,4,20,5,10,gaussian,0.0025,euclidean,0,1,0
1,2,2,1,none,1,13,11,17,14,gaussian,0.0050,euclidean,0,0,0
2,3,3,1,none,1,10,24,50,65,gaussian,0.0050,euclidean,0,0,0
3,4,4,1,none,1,5,15,8,15,linear,0.0050,euclidean,1,0,0
4,5,6,1,none,1,9,16,19,13,gaussian,0.0050,euclidean,0,0,0
5,6,7,1,none,1,50,90,50,55,tophat,0.0050,manhattan,1,0,1
6,7,8,2,tech,1,40,55,20,30,gaussian,0.0050,euclidean,0,0,0
7,8,10,1,none,1,6,12,9,14,gaussian,0.0050,euclidean,0,0,0
8,9,11,1,none,1,10,18,6,10,gaussian,0.0050,euclidean,0,0,0
9,10,12,1,none,1,17,50,5,30,gaussian,0.0050,euclidean,0,0,0

In [44]:
data.tail(20)

,new_part_id,participant_id,group_num,background,complexity,min_hotspots,max_hotspots,min_circles,max_circles,kernel,bandwidth,distance,k,b,d
160,43,53,3,professional,3,20,40,18,32,gaussian,0.0050,euclidean,0,0,0
161,44,54,1,none,3,3,15,3,15,gaussian,0.0050,euclidean,0,0,0
162,45,55,1,none,3,0,0,2,6,gaussian,0.0050,euclidean,0,0,0
163,46,56,1,none,3,27,30,27,30,gaussian,0.0050,euclidean,0,0,0
164,47,57,1,none,3,3,5,3,4,gaussian,0.0050,euclidean,0,0,0
165,48,58,1,none,3,20,45,20,35,gaussian,0.0050,euclidean,0,0,0
166,49,59,3,professional,3,8,15,50,60,gaussian,0.0050,euclidean,0,0,0
167,50,60,3,professional,3,6,8,30,38,gaussian,0.0050,euclidean,0,0,0
168,51,61,3,professional,3,18,33,19,36,gaussian,0.0050,euclidean,0,0,0
169,52,62,3,professional,3,10,15,15,20,gaussian,0.0050,euclidean,0,0,0
170,53,64,2,tech,3,15,22,8,12,gaussian,0.0075,manhattan,0,1,1
171,54,65,2,tech,3,5,30,5,15,gaussian,0.0025,euclidean,0,1,0
172,55,63,1,none,3,90,120,80,100,gaussian,0.0050,manhattan,0,0,1
173,56,66,2,tech,3,35,50,25,40,gaussian,0.0050,euclidean,0,0,0
174,57,67,1,none,3,7,12,15,25,gaussian,0.0050,euclidean,0,0,0
175,58,68,2,tech,3,70,100,60,115,tophat,0.0100,chebyshev,1,1,1
176,59,69,2,tech,3,3,6,8,13,gaussian,0.0050,euclidean,0,0,0
177,60,70,2,tech,1,6,12,11,15,gaussian,0.0050,euclidean,0,0,0
178,60,70,2,tech,2,12,19,6,15,tophat,0.0050,manhattan,1,0,1
179,60,70,2,tech,3,5,8,5,13,gaussian,0.0050,euclidean,0,0,0

In [45]:
data.to_csv('data/anovaFriendly.csv')