In [3]:
%matplotlib inline
#import seaborn as sns
#import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
#import sqlite3

survey_data = pd.read_csv('data/questionnaire.csv')
maps_data = pd.read_csv('data/map-data.csv')




survey_data['participant_id']=survey_data['Q51_1'].astype(np.int64)

survey_data.head(5)
survey_data.describe()

,Progress,Duration (in seconds),RecipientLastName,RecipientFirstName,RecipientEmail,ExternalReference,LocationLatitude,LocationLongitude,Q51_1,Q2_1,...,Q4_1,Q5_1,Q6_1,Q7_1,Q30_1,Q33_9_TEXT,Q44_1,Q51_1 - Sentiment Score,Q51_1 - Sentiment Polarity,participant_id
count,59.0,59.000000,0.0,0.0,0.0,0.0,59.000000,59.000000,59.000000,59.000000,...,59.000000,59.000000,59.000000,59.000000,59.000000,0.0,59.000000,50.000000,50.0,59.000000
mean,100.0,8290.000000,NaN,NaN,NaN,NaN,41.929228,-89.737303,35.542373,8.728814,...,3.355932,11.898305,6.864407,4.694915,26.949153,NaN,3.627119,0.200000,0.0,35.542373
std,0.0,19599.804026,NaN,NaN,NaN,NaN,2.328041,3.863701,20.820515,4.037883,...,3.066857,4.539842,4.439080,5.136933,10.404614,NaN,2.355465,0.571429,0.0,20.820515
min,100.0,604.000000,NaN,NaN,NaN,NaN,32.813705,-97.821999,1.000000,1.000000,...,0.000000,1.000000,0.000000,0.000000,20.000000,NaN,0.000000,-1.000000,0.0,1.000000
25%,100.0,1731.000000,NaN,NaN,NaN,NaN,43.038895,-87.935699,17.500000,5.000000,...,1.000000,9.000000,3.000000,1.000000,21.000000,NaN,2.000000,0.000000,0.0,17.500000
50%,100.0,2616.000000,NaN,NaN,NaN,NaN,43.038895,-87.906502,34.000000,8.000000,...,3.000000,12.000000,7.000000,3.000000,22.000000,NaN,4.000000,0.000000,0.0,34.000000
75%,100.0,4738.500000,NaN,NaN,NaN,NaN,43.038895,-87.906502,54.500000,12.000000,...,5.000000,15.000000,10.000000,7.000000,29.000000,NaN,5.000000,1.000000,0.0,54.500000
max,100.0,92662.000000,NaN,NaN,NaN,NaN,43.040695,-87.651703,69.000000,17.000000,...,10.000000,20.000000,18.000000,18.000000,76.000000,NaN,9.000000,1.000000,0.0,69.000000

In [4]:
data=pd.merge(maps_data, survey_data, on="participant_id", how="left")
data.describe()
data.head(5)
data.to_csv('data/masterData.csv', sep='\t')

In [5]:
data.describe()
data.head(5)

,new_part_id,participant_id,group_num,background,kernel1,bandwidth1,metric1,min_hotspots1,max_hotspots1,min_circles1,...,Q41,Q42,Q43,Q44_1,Q45,Q46,Q51_1 - Sentiment,Q51_1 - Sentiment Score,Q51_1 - Sentiment Polarity,Q51_1 - Topics
0,1,1,2,tech,gaussian,0.0025,euclidean,4,20,5,...,No,Neither agree nor disagree,Somewhat agree,5.0,Neutral,Neutral,NaN,NaN,NaN,NaN
1,2,2,1,none,gaussian,0.0050,euclidean,13,11,17,...,Yes,Somewhat agree,Somewhat disagree,2.0,Somewhat Libertarian,Somewhat fiscally conservative,Neutral,0.0,0.0,Unknown
2,3,3,1,none,gaussian,0.0050,euclidean,10,24,50,...,Yes,Agree,Somewhat agree,9.0,Authoritarian,Fiscally conservative,Neutral,0.0,0.0,Unknown
3,4,4,1,none,linear,0.0050,euclidean,5,15,8,...,No,Agree,Agree,5.0,Neutral,Somewhat fiscally conservative,Neutral,0.0,0.0,Unknown
4,5,6,1,none,gaussian,0.0050,euclidean,9,16,19,...,Yes,Agree,Somewhat agree,1.0,Somewhat Authoritarian,Somewhat fiscally conservative,Neutral,0.0,0.0,Unknown

In [6]:
data_g1= data[data['group_num']==1]

data_g1.to_csv('data/g1.csv', sep='\t')

In [7]:
data_g2= data[data['group_num']==2]

data_g2.to_csv('data/g2.csv', sep='\t')

In [8]:
data_g3= data[data['group_num']==3]

data_g3.to_csv('data/g3.csv', sep='\t')